# Generated by Django 3.2 on 2021-04-25 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField()),
                ('created_data', models.DateTimeField(auto_now=True)),
                ('updated_data', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('tender_start_date', models.DateTimeField(null=True)),
                ('tender_end_date', models.DateTimeField(null=True)),
                ('last_status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenders', models.ManyToManyField(to='MonitoringService.Tender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
