# Generated by Django 3.2 on 2021-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringService', '0003_rename_userstat_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
