# Generated by Django 3.2 on 2021-07-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringService', '0006_alter_tender_status_monitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='status_monitoring',
        ),
    ]
