# Generated by Django 3.2 on 2021-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringService', '0010_remove_tender_status_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='status_monitoring',
            field=models.BooleanField(null=True),
        ),
    ]
