# Generated by Django 3.2 on 2021-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringService', '0012_alter_tender_status_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
